export { alimentos } from './alimentos.json'
export { animales } from './animales.json'
export { mediosComunicacion } from './mediosComunicacion.json'
export { profesiones } from './profesiones.json'
export { transporte } from './transporte.json'
